### ISSUE TITLE
Changing network/subnet properties does not update deployment

### ISSUE THREAD

**Issue by ocervell** [terraform-google-modules/terraform-google-network#10] opened 2018-09-17 19:50 UTC
Steps to reproduce:

```hcl
module "vpc-network" {
  source       = "github.com/terraform-google-modules/terraform-google-network"
  project_id   = "${module.vpc-host.project_id}"
  network_name = "tf-training-network"

  subnets = [
    {
      subnet_name   = "gke-prod"
      subnet_ip     = "10.0.0.0/17"
      subnet_region = "us-east1"
    },
    {
      subnet_name   = "gke-dev"
      subnet_ip     = "10.1.0.0/17"
      subnet_region = "us-east1"
    }
  ]

  secondary_ranges = {
    gke-prod = []
    gke-dev = []
  }
}
```

Add `subnet_flow_logs = true` to one of the subnets and get no new changes when running `terraform apply`. Same for other additional flags passed to any subnet.

Update: This is the same when adding `shared_vpc_host = true` (meaning we can't currently convert a vpc to a shared vpc)

**Comment by morgante** [comment] 2018-09-24 16:28
@andreyk-code Maybe we should standardize on using string variables? (ie `"true" for subnet_flow_logs`)

**Comment by morgante** [comment] 2018-09-24 16:50
#9 to track that standardization.

Closing this as @andreyk-code and I cannot reproduce. @ocervell reopen if you have reproduction.

**Closed by morgante** 2018-09-24 16:50 UTC
